Add Prism Launcher (Minecraft) blogpost
stuylinux/stuylinux.org pull request #15
Opened 2023-04-14 03:04 UTC by TheEgghead27

2023-04-14 03:05 UTC, TheEgghead27 commented
WIP w/ @thegu5

2023-04-16 19:45 UTC, TheEgghead27 commented
*known bug: current rendering does not give id to headers

2023-04-16 20:01 UTC, thegu5 requested changes

2023-04-16 20:01 UTC, thegu5 commented on _posts/minecraft-prismlauncher.md
> +Use the sign in options on the right-hand side of the menu to sign in to your Minecraft account (Microsoft or Mojang).
```suggestion
Use the sign in options on the right-hand side of the menu to sign in with your Minecraft (Microsoft) account. Although an option for Mojang accounts is provided, they have been phased out - so if you still have one, follow [this guide from Microsoft](https://help.minecraft.net/hc/en-us/articles/4403181904525).
```

2023-04-16 20:01 UTC, thegu5 commented on _posts/minecraft-prismlauncher.md
> +#### OptiFine
This optifine jar can also be used as a forge mod, which is simpler (?).

2023-04-16 20:01 UTC, thegu5 commented on _posts/minecraft-prismlauncher.md
> +A modern way to optimize Minecraft is to use the Fabric mod launcher with tools like Sodium, Lithium, and Phosphor, along with Iris Shaders to provide compatibility with OptiFine shaders.
```suggestion
A modern way to optimize Minecraft is to use the Fabric mod loader with tools like Sodium, Lithium, and Phosphor, along with Iris Shaders to provide compatibility with OptiFine shaders.
```

2023-04-16 20:01 UTC, thegu5 commented on _posts/minecraft-prismlauncher.md
> +First, right-click and edit the instance settings.
Could also make this a new instance (show off how easy it is to have multiple instances side by side?)

2023-04-16 21:49 UTC, TheEgghead27 commented on _posts/minecraft-prismlauncher.md
> +#### OptiFine
True but it isn't on CurseForge so it'd be just mediocre

2023-04-16 23:48 UTC, TheEgghead27 commented on _posts/minecraft-prismlauncher.md
> +First, right-click and edit the instance settings.
Added

2023-04-17 00:10 UTC, TheEgghead27 commented on _posts/minecraft-prismlauncher.md
> +### Reviewed by: {gus} [@thegu5](https://github.com/thegu5)
Oh @thegu5 lmk how you want your name to look down here

2023-04-18 02:13 UTC, thegu5 commented on _posts/minecraft-prismlauncher.md
> +### Reviewed by: {gus} [@thegu5](https://github.com/thegu5)
```suggestion
### Reviewed by: Gus [@thegu5](https://github.com/thegu5)
```

2023-04-18 02:16 UTC, thegu5 approved these changes

2023-04-18 02:16 UTC, TheEgghead27 commented
@leomet07 have at it! lemme know when it's up so i can announce on the proper channels

2023-04-22 16:03 UTC, leomet07 approved these changes
LGTM! nice work !

2023-04-22 16:04 UTC, merged